import type { NotificationTypeDefinition } from '../notifications/notification-types.registry';

export const OPD_NOTIFICATION_TYPES: NotificationTypeDefinition[] = [
  {
    key: 'opd.claim-submitted',
    name: 'Medical claim submitted',
    description: 'Sent to Finance when an employee submits a claim.',
    severity: 'info',
    defaultChannels: ['in_app'],
    titleTemplate: 'New medical claim {{claimNumber}}',
    bodyTemplate: '{{employeeName}} submitted a medical claim for {{amountPkr}}.',
    linkTemplate: '/opd/claims/{{claimId}}',
    module: 'opd',
  },
  {
    key: 'opd.claim-submitted-employee',
    name: 'Your claim was submitted',
    description: 'Confirmation to the employee after submit.',
    severity: 'info',
    defaultChannels: ['in_app'],
    titleTemplate: 'Claim {{claimNumber}} submitted',
    bodyTemplate: 'Your medical claim has been submitted and is awaiting Finance review.',
    linkTemplate: '/opd/claims/{{claimId}}',
    module: 'opd',
  },
  {
    key: 'opd.claim-approved',
    name: 'Medical claim approved',
    severity: 'success',
    defaultChannels: ['in_app', 'email'],
    titleTemplate: 'Claim {{claimNumber}} approved',
    bodyTemplate: 'Your medical claim has been approved. {{note}}',
    linkTemplate: '/opd/claims/{{claimId}}',
    module: 'opd',
  },
  {
    key: 'opd.claim-rejected',
    name: 'Medical claim rejected',
    severity: 'danger',
    defaultChannels: ['in_app', 'email'],
    titleTemplate: 'Claim {{claimNumber}} rejected',
    bodyTemplate: 'Your medical claim was rejected. Reason: {{reason}}',
    linkTemplate: '/opd/claims/{{claimId}}',
    module: 'opd',
  },
  {
    key: 'opd.claim-returned',
    name: 'Medical claim returned',
    severity: 'warning',
    defaultChannels: ['in_app', 'email'],
    titleTemplate: 'Claim {{claimNumber}} needs changes',
    bodyTemplate: 'Your medical claim was returned for correction. {{feedback}}',
    linkTemplate: '/opd/claims/{{claimId}}',
    module: 'opd',
  },
];
