import type { NotificationTypeDefinition } from '../notifications/notification-types.registry';

export const EXPENSE_NOTIFICATION_TYPES: NotificationTypeDefinition[] = [
  {
    key: 'expenses.claim-submitted',
    name: 'Expense claim submitted',
    description: 'Sent to Finance when an employee submits a claim.',
    severity: 'info',
    defaultChannels: ['in_app'],
    titleTemplate: 'New expense {{claimNumber}}',
    bodyTemplate: '{{employeeName}} submitted a {{category}} claim for {{amount}}.',
    linkTemplate: '/expenses/claims/{{claimId}}',
    module: 'expenses',
  },
  {
    key: 'expenses.claim-submitted-employee',
    name: 'Your expense was submitted',
    description: 'Confirmation to the employee after submit.',
    severity: 'info',
    defaultChannels: ['in_app'],
    titleTemplate: 'Claim {{claimNumber}} submitted',
    bodyTemplate: 'Your expense claim has been submitted and is awaiting Finance review.',
    linkTemplate: '/expenses/claims/{{claimId}}',
    module: 'expenses',
  },
  {
    key: 'expenses.claim-approved',
    name: 'Expense claim approved',
    severity: 'success',
    defaultChannels: ['in_app', 'email'],
    titleTemplate: 'Claim {{claimNumber}} approved',
    bodyTemplate: 'Your expense claim has been approved. {{note}}',
    linkTemplate: '/expenses/claims/{{claimId}}',
    module: 'expenses',
  },
  {
    key: 'expenses.claim-rejected',
    name: 'Expense claim rejected',
    severity: 'danger',
    defaultChannels: ['in_app', 'email'],
    titleTemplate: 'Claim {{claimNumber}} rejected',
    bodyTemplate: 'Your expense claim was rejected. Reason: {{reason}}',
    linkTemplate: '/expenses/claims/{{claimId}}',
    module: 'expenses',
  },
  {
    key: 'expenses.claim-returned',
    name: 'Expense claim returned',
    severity: 'warning',
    defaultChannels: ['in_app', 'email'],
    titleTemplate: 'Claim {{claimNumber}} needs changes',
    bodyTemplate: 'Your expense claim was returned for correction. {{feedback}}',
    linkTemplate: '/expenses/claims/{{claimId}}',
    module: 'expenses',
  },
];
