'use client';

import * as React from 'react';
import { CheckCircle2, ClipboardCheck } from 'lucide-react';
import { toast } from 'sonner';
import type { ReminderTaskPublic, ReminderTaskStatus } from '@futurenostics/types';
import { AppShell } from '@/components/shell/app-shell';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Skeleton } from '@/components/ui/skeleton';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { useCompleteReminderTask, useReminderTasks } from '@/lib/queries/reminder-tasks';

type FilterKey = 'open' | 'overdue' | 'completed';

const FILTER_QUERY: Record<FilterKey, { status?: ReminderTaskStatus; overdue?: boolean }> = {
  open: { status: 'open' },
  overdue: { overdue: true },
  completed: { status: 'completed' },
};

export default function ReminderTasksPage() {
  const [filter, setFilter] = React.useState<FilterKey>('open');
  const tasks = useReminderTasks(FILTER_QUERY[filter]);
  const complete = useCompleteReminderTask();

  async function onComplete(task: ReminderTaskPublic) {
    const note = window.prompt(`Complete "${task.title}"? Optional note:`, '');
    if (note === null) return; // cancelled
    try {
      await complete.mutateAsync({ id: task.id, data: { note: note.trim() || undefined } });
      toast.success('Task completed');
    } catch (e) {
      toast.error((e as Error).message);
    }
  }

  const items = tasks.data?.items ?? [];

  return (
    <AppShell breadcrumbs={[{ label: 'Reminders & Reviews' }, { label: 'Reminder Tasks' }]}>
      <div className="gap-fn-5 mx-auto flex w-full max-w-[1120px] flex-col">
        <div className="gap-fn-2 flex flex-col">
          <h1
            className="text-fn-fg font-fn-semibold text-[22px]"
            style={{ letterSpacing: '-0.02em' }}
          >
            Reminder Tasks
          </h1>
          <p className="text-fn-fg-muted max-w-[680px] text-[13px]">
            Evaluation and review tasks generated by reminder rules. HR is nudged automatically
            until each task is completed — overdue tasks are flagged.
          </p>
          {tasks.data && (
            <div className="gap-fn-2 flex flex-wrap">
              <Badge tone="info">{tasks.data.openCount} open</Badge>
              {tasks.data.overdueCount > 0 && (
                <Badge tone="danger">{tasks.data.overdueCount} overdue</Badge>
              )}
            </div>
          )}
        </div>

        <Tabs value={filter} onValueChange={(v) => setFilter(v as FilterKey)}>
          <TabsList>
            <TabsTrigger value="open">Open</TabsTrigger>
            <TabsTrigger value="overdue">Overdue</TabsTrigger>
            <TabsTrigger value="completed">Completed</TabsTrigger>
          </TabsList>
        </Tabs>

        {tasks.isPending ? (
          <Skeleton className="h-[320px] w-full" />
        ) : items.length === 0 ? (
          <div className="border-fn-border bg-fn-bg-panel rounded-fn-xs py-fn-16 gap-fn-2 flex flex-col items-center border text-center">
            <ClipboardCheck className="text-fn-fg-faint h-fn-8 w-fn-8" />
            <p className="text-fn-fg font-fn-semibold">No {filter} tasks</p>
            <p className="text-fn-fg-muted text-[13px]">
              {filter === 'open'
                ? 'Nothing pending right now.'
                : filter === 'overdue'
                  ? 'No overdue tasks — nicely kept up.'
                  : 'No completed tasks yet.'}
            </p>
          </div>
        ) : (
          <div className="border-fn-border bg-fn-bg-panel rounded-fn-xs overflow-hidden border">
            <div className="overflow-x-auto">
              <table className="w-full text-[12.5px]">
                <thead className="bg-fn-bg-inset text-fn-fg-faint font-fn-semibold tracking-fn-uppercase-tight text-[10.5px] uppercase">
                  <tr>
                    <th className="px-fn-4 py-fn-2_5 text-left">Task</th>
                    <th className="px-fn-4 py-fn-2_5 text-left">Subject</th>
                    <th className="px-fn-4 py-fn-2_5 text-left">Assignee</th>
                    <th className="px-fn-4 py-fn-2_5 text-left">Due</th>
                    <th className="px-fn-4 py-fn-2_5 text-center">Nudges</th>
                    <th className="px-fn-4 py-fn-2_5 text-left">Status</th>
                    <th className="px-fn-4 py-fn-2_5 text-right">Action</th>
                  </tr>
                </thead>
                <tbody>
                  {items.map((t) => (
                    <tr key={t.id} className="border-fn-divider border-t">
                      <td className="px-fn-4 py-fn-2_5">
                        <span className="text-fn-fg font-fn-medium">{t.title}</span>
                      </td>
                      <td className="px-fn-4 py-fn-2_5 text-fn-fg-muted">
                        {t.subjectLabel ?? '—'}
                      </td>
                      <td className="px-fn-4 py-fn-2_5 text-fn-fg-muted">
                        {t.assigneeName ?? '—'}
                      </td>
                      <td className="px-fn-4 py-fn-2_5 text-fn-fg-muted tabular-nums">
                        {formatDate(t.dueDate)}
                      </td>
                      <td className="px-fn-4 py-fn-2_5 text-fn-fg-faint text-center tabular-nums">
                        {t.followUpCount}
                      </td>
                      <td className="px-fn-4 py-fn-2_5">
                        <StatusBadge task={t} />
                      </td>
                      <td className="px-fn-4 py-fn-2_5 text-right">
                        {t.status === 'open' ? (
                          <Button
                            variant="ghost"
                            size="sm"
                            disabled={complete.isPending}
                            onClick={() => onComplete(t)}
                          >
                            <CheckCircle2 className="h-fn-3_5 w-fn-3_5" /> Complete
                          </Button>
                        ) : (
                          <span className="text-fn-fg-faint text-[11px]">
                            {t.completedByName ? `by ${t.completedByName}` : '—'}
                          </span>
                        )}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </div>
    </AppShell>
  );
}

function StatusBadge({ task }: { task: ReminderTaskPublic }) {
  if (task.status === 'completed') return <Badge tone="success">Completed</Badge>;
  if (task.status === 'cancelled') return <Badge tone="default">Cancelled</Badge>;
  if (task.overdue) return <Badge tone="danger">Overdue</Badge>;
  return <Badge tone="warning">Open</Badge>;
}

function formatDate(iso: string): string {
  return new Date(iso).toLocaleDateString('en-US', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
  });
}
