import type { ExpenseClaimStatus } from '@futurenostics/types';

export const EXPENSE_STATUS_LABEL: Record<ExpenseClaimStatus, string> = {
  draft: 'Not submitted',
  pending_approval: 'Pending approval',
  returned: 'Returned for correction',
  approved: 'Approved',
  rejected: 'Rejected',
};

export const EXPENSE_COPY = {
  moduleName: 'Expenses',
  newExpense: 'New expense',
  submitToFinance: 'Submit for approval',
  submitSuccess: 'Submitted for approval.',
  saveChanges: 'Save changes',
  saveChangesSuccess: 'Changes saved.',

  listMineTitle: 'My expenses',
  listAllTitle: 'Expense claims',
  pageIntroOwn: 'Pending and returned claims waiting on you or Finance.',
  pageIntroHistory: 'Your approved and rejected expenses.',
  orgHistoryIntro: 'Approved and rejected expense claims across the organization.',

  listEmptyTitle: 'No active expenses',
  listEmptyHint: 'Start a claim with New expense. Attach a receipt or invoice.',
  listEmptyHistoryTitle: 'No past expenses',
  listEmptyHistoryHint: 'Approved and rejected claims will show up here.',
  listEmptyFiltered: 'No claims match this filter.',
  listLoadError: 'Could not load expenses.',
  claimLoadError: 'Could not load this claim.',
  noAccessTitle: 'No access',
  noAccessBody: 'You do not have permission to view expense claims.',
  portalTab: 'Expenses',

  colClaimNumber: 'Claim #',
  colCategory: 'Category',
  colAmount: 'Amount',
  colCreated: 'Created',
  expenseMonthLabel: 'Expense month',
  amountLabel: 'Amount (PKR)',
  amountInvalid: 'Enter a valid amount.',
  descriptionLabel: 'Description',
  descriptionPlaceholder: 'What was this expense for?',

  categoryLabel: 'Category',
  categoryHint: 'What kind of expense is this?',
  medicalSubLabel: 'Medical type',
  gymAmountMax: 'Gym reimbursement cannot exceed ₨2,000 per claim.',

  documentsLabel: 'Receipt / supporting document',
  documentsRequired: 'Add at least one receipt or supporting document.',
  documentsEmpty: 'No files yet.',
  documentsSectionTitle: 'Receipt / supporting document',
  addDocument: 'Add file',
  addAnotherDocument: 'Add another file',
  filePickerHint: 'JPEG, PNG, WebP, or PDF · 5 MB each',
  documentsUploadSuccess: 'Document added.',
  documentsRemoveSuccess: 'Document removed.',
  documentsCount: (n: number, max: number) => `${n} of ${max} files`,

  filterStatusAll: 'All',
  filterStatusPending: EXPENSE_STATUS_LABEL.pending_approval,
  filterStatusReturned: EXPENSE_STATUS_LABEL.returned,
  filterStatusApproved: EXPENSE_STATUS_LABEL.approved,
  filterStatusRejected: EXPENSE_STATUS_LABEL.rejected,
  sortLabel: 'Sort by',
  sortNewest: 'Newest',
  sortOldest: 'Oldest',
  sortAmountHigh: 'High to Low',
  sortAmountLow: 'Low to High',

  historyTitle: 'History',
  approveClaim: 'Approve',
  approveDialogTitle: 'Approve claim',
  rejectClaim: 'Reject',
  returnForCorrection: 'Return for correction',
  alertPendingTitle: 'Pending approval',
  alertPendingBody: 'Finance has not decided on this claim yet.',
  alertApprovedTitle: 'Approved',
  alertApprovedBody: 'This claim was approved.',
  alertRejectedTitle: 'Rejected',
  alertRejectedNoReason: 'No rejection reason was provided.',
  alertReturnedTitle: 'Returned for correction',
  alertReturnedBody:
    'Finance asked you to update this claim and submit again. Your previous submission is not approved yet.',
  lastActionBy: 'by',
  expenseMonthRequired: 'Add the expense month.',
  descriptionRequired: 'Add a description.',
};
