/**
 * Scheduled monthly report email (Module 5 — §7 💡 suggestion).
 *
 * At 06:00 Asia/Karachi on the 1st of each month, generate the PREVIOUS
 * month's Monthly Commission Summary (XLSX) and email it to everyone who
 * can manage the report schedule — Finance Manager + Super Admin by
 * default (resolved by the `reports:manage_schedule` permission, not a
 * hard-coded role list, so custom roles that hold the grant are included
 * automatically).
 *
 * Idempotent: BullMQ keys the repeatable by (name + pattern + tz), so
 * re-adding on every boot just refreshes the entry. Skipped entirely in
 * NODE_ENV=test.
 */
import {
  Inject,
  Injectable,
  Logger,
  type OnApplicationBootstrap,
  type OnModuleDestroy,
} from '@nestjs/common';
import { prisma } from '@futurenostics/db';
import { Queue, Worker, type Job } from 'bullmq';
import type IORedis from 'ioredis';
import { AppConfigService } from '../../config/app.config';
import { BULL_REDIS_CONNECTION } from '../../core/scheduler/scheduler.module';
import { EmailService } from '../../core/email/email.service';
import { renderReport } from '../../core/reports/report-formats';
import { monthLabel } from '../commissions/commission-calc';
import { findReportDefinition } from './report-definitions';
import { ReportsService } from './reports.service';

const QUEUE_NAME = 'reports';
const JOB_NAME = 'monthly-summary';
const CRON = '0 6 1 * *'; // 06:00 on the 1st of the month
const TZ = 'Asia/Karachi';

@Injectable()
export class ReportSchedulerService implements OnApplicationBootstrap, OnModuleDestroy {
  private readonly logger = new Logger(ReportSchedulerService.name);
  private queue: Queue | null = null;
  private worker: Worker | null = null;

  constructor(
    @Inject(BULL_REDIS_CONNECTION) private readonly redis: IORedis,
    private readonly config: AppConfigService,
    private readonly reports: ReportsService,
    private readonly email: EmailService,
  ) {}

  async onApplicationBootstrap(): Promise<void> {
    if (this.config.env.NODE_ENV === 'test') return;

    this.queue = new Queue(QUEUE_NAME, { connection: this.redis });
    this.worker = new Worker(QUEUE_NAME, (job) => this.handle(job), { connection: this.redis });
    this.worker.on('failed', (job, err) => {
      this.logger.error(`Job ${job?.id ?? '?'} failed: ${err.message}`, err.stack);
    });

    await this.queue.add(
      JOB_NAME,
      {},
      { repeat: { pattern: CRON, tz: TZ }, jobId: 'reports-monthly-summary' },
    );
    this.logger.log(`Scheduled monthly report email: '${CRON}' ${TZ} (queue=${QUEUE_NAME})`);
  }

  async onModuleDestroy(): Promise<void> {
    await this.worker?.close();
    await this.queue?.close();
  }

  /** Previous month as 'YYYY-MM' relative to `ref`. */
  private previousMonthKey(ref: Date): string {
    const d = new Date(Date.UTC(ref.getUTCFullYear(), ref.getUTCMonth() - 1, 1));
    return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}`;
  }

  private async handle(_job: Job): Promise<void> {
    await this.runMonthlySummary();
  }

  /** Exposed for the manifest's scheduledJob handler + manual triggers. */
  async runMonthlySummary(): Promise<void> {
    const monthKey = this.previousMonthKey(new Date());
    const label = monthLabel(monthKey);

    const recipients = await prisma.user.findMany({
      where: {
        isActive: true,
        roles: {
          some: {
            role: { permissions: { some: { permission: { key: 'reports:manage_schedule' } } } },
          },
        },
      },
      select: { email: true },
    });
    const to = [...new Set(recipients.map((r) => r.email))];
    if (!to.length) {
      this.logger.warn(`monthly summary ${monthKey}: no recipients (reports:manage_schedule)`);
      return;
    }

    const def = findReportDefinition('monthly-commission-summary');
    if (!def) return;
    const data = await this.reports.buildData(def, { monthKey }, /* includeSalary */ true);
    const xlsx = await renderReport(data, 'xlsx');

    await this.email.send({
      to,
      subject: `Commission Summary — ${label}`,
      html:
        `<p>Attached is the automated commission summary for <strong>${label}</strong>.</p>` +
        `<p>${data.rows.length} recipient(s). Generated by Futurenostics HRMS.</p>`,
      attachments: [
        {
          filename: `commission-summary-${monthKey}.xlsx`,
          content: xlsx,
          contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        },
      ],
    });
    this.logger.log(`monthly summary ${monthKey}: emailed ${to.length} recipient(s)`);
  }
}
